export const stateOptions = [
    { text: "Alabama, AL", value: "Alabama, AL" },
    { text: "Alaska, AK", value: "Alaska, AK"},
    { text: "Arizona, AZ", value: "Arizona, AZ"},
    { text: "Arkansas, AR", value: "Arkansas, AR" },
    { text: "California, CA", value: "California, CA" },
    { text: "Colorado, CO", value: "Colorado, CO" },
    { text: "Connecticut, CT", value: "Connecticut, CT" },
    { text: "Delaware, DE", value: "Delaware, DE" },
    { text: "Florida, FL", value: "Florida, FL" },
    { text: "Georgia, GA", value: "Georgia, GA" },
    { text: "Hawaii, HI", value: "Hawaii, HI" },
    { text: "Idaho, ID", value: "Idaho, ID" },
    { text: "Illinois, IL", value: "Illinois, IL" },
    { text: "Indiana, IN", value: "Indiana, IN" },
    { text: "Iowa, IA", value: "Iowa, IA" },
    { text: "Kansas, KS", value: "Kansas, KS" },
    { text: "Kentucky, KY", value: "Kentucky, KY" },
    { text: "Louisiana, LA", value: "Louisiana, LA" },
    { text: "Maine, ME", value: "Maine, ME" },
    { text: "Maryland, MD", value: "Maryland, MD" },
    { text: "Massachusetts, MA", value: "Massachusetts, MA" },
    { text: "Michigan, MI", value: "Michigan, MI" },
    { text: "Minnesota, MN", value: "Minnesota, MN" },
    { text: "Mississippi, MS", value: "Mississippi, MS" },
    { text: "Missouri, MO", value: "Missouri, MO" },
    { text: "Montana, MT", value: "Montana, MT" },
    { text: "Nebraska, NE", value: "Nebraska, NE" },
    { text: "Nevada, NV", value: "Nevada, NV" },
    { text: "New Hampshire, NH", value: "New Hampshire, NH" },
    { text: "New Jersey, NJ", value: "New Jersey, NJ" },
    { text: "New Mexico, NM", value: "New Mexico, NM" },
    { text: "New York, NY", value: "New York, NY" },
    { text: "North Carolina, NC", value: "North Carolina, NC" },
    { text: "North Dakota, ND", value: "North Dakota, ND" },
    { text: "Ohio, OH", value: "Ohio, OH" },
    { text: "Oklahoma, OK", value: "Oklahoma, OK" },
    { text: "Oregon, OR", value: "Oregon, OR" },
    { text: "Pennsylvania, PA", value: "Pennsylvania, PA" },
    { text: "Rhode Island, RI", value: "Rhode Island, RI" },
    { text: "South Carolina, SC", value: "South Carolina, SC" },
    { text: "South Dakota, SD", value: "South Dakota, SD" },
    { text: "Tennessee, TN", value: "Tennessee, TN" },
    { text: "Texas, TX", value: "Texas, TX" },
    { text: "Utah, UT", value: "Utah, UT" },
    { text: "Vermont, VT", value: "Vermont, VT" },
    { text: "Virginia, VA", value: "Virginia, VA" },
    { text: "Washington, WA", value: "Washington, WA" },
    { text: "West Virginia, WV", value: "West Virginia, WV" },
    { text: "Wisconsin, WI", value: "Wisconsin, WI" },
    { text: "Wyoming, WY", value: "Wyoming, WY" },
]